### ISSUE TITLE
Exam 1 data question

### ISSUE THREAD

**Issue by Komegaga** [CheyiLin/data-engineer-exam#2]
Hi @CheyiLin,

Do I need to analyze the 67 time series data separately or together? Thanks.

**Comment by CheyiLin** [comment]
Hi @Komegaga,

Thanks for asking the question.

Could you please modify the issue and describe the question in English? This is also a test.
Thank you.

@nailo2c FYI.

**Comment by nailo2c** [comment]
Hi @Komegaga , please analyze the 67 time series data separately, thanks!

**Comment by nailo2c** [comment]
@Komegaga Could you open the issue on your repo? And if you have any questions, please don't hesitate to ask me.

**Comment by CheyiLin** [comment]
@nailo2c Thanks! I didn't even notice that.

@Komegaga Please enable the feature **Issue** in your repo so I can transfer this issue to your repo, thanks.

**Comment by Komegaga** [comment]
@nailo2c Thanks for response.
@CheyiLin I already enable the Issue feature, thanks.

**Comment by CheyiLin** [comment]
Just found that cannot transfer issues across different owners/orgs repositories ([docs](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository)), will delete this issue now.
